title: "Davide Gramuglia — Security Analyst"
description: "Blue-Team / SOC — network-focused, DFIR-curious. Building detections, small SOC labs, and clean write-ups."
theme: jekyll-theme-hacker
show_downloads: false
permalink: pretty
